### ISSUE TITLE
这个项目的作者太强了怎么办啊

### ISSUE THREAD

**Issue by Officeyutong** [lxlonlyn/Monopoly#6]
如题
![UD2L3 9Q 2HS29)075 F6BG](https://user-images.githubusercontent.com/9004058/94364119-a3ce6000-00f9-11eb-8262-ba7718a42dfd.png)

**Comment by truemogician** [comment]
太强了UD2L3 9Q 2HS29)075 F6BG

**Comment by truemogician** [comment]
****！

**Comment by lxlonlyn** [comment]
这也能%？
